version: '3.8'

services:
  h2:
    image: oscarfonts/h2
    container_name: h2-db
    ports:
      - "1521:1521"   # Port f√ºr JDBC
      - "81:81"       # Web-Console
    environment:
      H2_OPTIONS: "-ifNotExists"
    volumes:
      - h2-data:/opt/h2-data

  app:
    build: ../Node-Docker-CI
    container_name: my-github-app
    ports:
      - "8080:8080"
    depends_on:
      - h2
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2-db:1521/~/test
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:

volumes:
  h2-data:

